server:
  port: 9000
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://shopperdb.c4biysdam7a3.us-east-1.rds.amazonaws.com:3306/shopperdb
    username: tcsyellow
    password: tcsyellow
